mini: use explicit loop device for root mount
Starting in some 6.x version the automatic loop device assigned by
'mount -o loop' was impossible to delete by 'losetup -d'. This caused
cortuptions after updating distro or kernel. 'fsck' was able to fix most
of that but that's not reliable.

Work around that by allocating the loop device before mount, but reuse
the same device if there's one.

Signed-off-by: David Sterba <dave@jikos.cz>

diff --git a/mini/root-mount b/mini/root-mount
--- a/mini/root-mount
+++ b/mini/root-mount
@@ -2,5 +2,11 @@
 
 mkdir -p mnt
 if ! findmnt mnt; then
-	sudo mount -o loop root mnt
+	lo=$(sudo losetup --verbose --show --find --nooverlap root)
+	if [ $? != 0 ]; then
+		echo "ERROR: cannot find loop device for mount"
+		exit 1
+	fi
+	echo "Mount (re)use device $lo"
+	sudo mount "$lo" mnt
 fi
