mini: don't fail if chattr +C is not supported
NOCOW files are preferred on btrfs but runme should not fail there on
other filesystems.

Signed-off-by: David Sterba <dave@jikos.cz>

diff --git a/mini/runme b/mini/runme
--- a/mini/runme
+++ b/mini/runme
@@ -27,7 +27,8 @@ function reset_drives() {
 		if $cleandisk; then
 			truncate -s 0 "$p"
 		fi
-		chattr +C "$p"
+		# on btrfs we need +C, otherwise don't want to fail
+		chattr +C "$p" || true
 		if $fallocate; then
 			fallocate -l 12G "$p"
 		else
